# Generated by Django 6.0 on 2025-12-05 05:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_picture', models.ImageField(default='https://www.piclumen.com/text-to-image/', upload_to='profile_pictures/')),
                ('programing_language', models.CharField(choices=[('PYTHON', 'python3.12.3'), ('C', 'gcc 13.3.0'), ('JAVA', 'openjdk 21.0.2')], default='PYTHON', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DMRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_deltas', models.JSONField(blank=True, null=True)),
                ('time_labels', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField(blank=True, default='', null=True)),
                ('attempt_at', models.TimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('teachers_remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempt_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptPaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('start_line', models.PositiveIntegerField(default=0)),
                ('end_line', models.PositiveIntegerField(default=0)),
                ('attempt_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasted_attempt_test', to='editor.attempttest')),
            ],
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels_file', to='editor.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='codefile',
            field=models.ManyToManyField(related_name='channels_file', to='editor.codefile'),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text_question', models.TextField(blank=True, null=True)),
                ('raw_question_text', models.TextField(blank=True, null=True)),
                ('image_question', models.ImageField(blank=True, null=True, upload_to='lab-question/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=10)),
                ('start_at', models.TimeField(auto_now_add=True, null=True)),
                ('end_at', models.TimeField(blank=True, null=True)),
                ('test_marks', models.FloatField(default=10)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labtest', to='editor.channel')),
            ],
        ),
        migrations.AddField(
            model_name='attempttest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labtest_attempt', to='editor.labtest'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64)),
                ('installed_packages', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='editor.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='editor.dmroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='editor.roommessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='editor.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='dmroom',
            name='participant',
            field=models.ManyToManyField(to='editor.userprofile'),
        ),
        migrations.AddField(
            model_name='codefile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_file', to='editor.userprofile'),
        ),
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to='editor.userprofile'),
        ),
        migrations.AddField(
            model_name='channel',
            name='has_permission',
            field=models.ManyToManyField(blank=True, related_name='task_permission', to='editor.userprofile'),
        ),
        migrations.AddField(
            model_name='channel',
            name='participants',
            field=models.ManyToManyField(to='editor.userprofile'),
        ),
    ]
