# Generated by Django 5.1.6 on 2025-09-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0035_attempttest_ai_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_picture',
            field=models.ImageField(default='https://www.piclumen.com/text-to-image/', upload_to='profile_pictures/'),
        ),
    ]
