# Generated by Django 5.1.6 on 2025-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0036_alter_channel_channel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttest',
            name='code',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
