# Generated by Django 5.1.6 on 2025-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0037_alter_attempttest_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttest',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempttest',
            name='teachers_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_marks',
            field=models.FloatField(default=10),
        ),
    ]
